apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: nginx
          image: nginx:1.21.6
          ports:
            - containerPort: 443
          volumeMounts:
            - name: nginx-certs
              mountPath: /etc/nginx/certs
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/
              
        - name: petclinic
          image: balaji36490/petclinic:3f3abd6
          ports:
            - containerPort: 8080

      volumes:
        - name: nginx-certs
          secret:
            secretName: backend
        - name: nginx-config
          configMap:
            name: nginx-config
            