apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress-service
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway  
spec:
  tls:
    - secretName: petclinic
  # ingressClassName: azure-application-gateway
  rules:
    # - host: pet.petclinic.com
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: petclinic
                port:
                  number: 8080
          
