name: Deploying on the AKS

on: 
  workflow_dispatch:
  

permissions:
      contents: read
      id-token: write

jobs:
  deploying-on-aks:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: main
    

      - name: azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}  
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Installing the kubelogin
        run: |
          curl -L -o kubelogin.zip https://github.com/Azure/kubelogin/releases/download/v0.0.26/kubelogin-linux-amd64.zip
          unzip kubelogin.zip
          sudo mv bin/linux_amd64/kubelogin /usr/local/bin
          kubelogin --version

      - name: Deploy to Azure kubernetes
        run: |
          az account show
          az aks get-credentials --resource-group aksrg --name myaks-cluster
          # kubelogin convert-kubeconfig -l workloadidentity --client-id "${{ secrets.AZURE_CLIENT_ID }}" --tenant-id "${{ secrets.AZURE_TENANT_ID }}" 
          kubelogin convert-kubeconfig -l azurecli
          kubectl apply -f ./spring-petclinic/manifests/

