# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven latest

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name : checking the current folder
        run: pwd && ls -l


      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven

      - name: installing maven
        run: |
            sudo apt-get update
            sudo apt-get install -y maven
            mvn --version 
      - name: build the project
        run: |
            mvn -B package --file ./spring-petclinic/pom.xml

      - name: view the test file
        run: |
            ls -l ./spring-petclinic/target/
            ls -l ./spring-petclinic/target/surefire-reports/
            cat ./spring-petclinic/target/surefire-reports/*.txt
            
          
      # - name: Make mvnw executable
      #   run: chmod +x ./spring-petclinic/mvnw

      # - name: Build with Maven Wrapper 
      #   working-directory: ./spring-petclinic
      #   run: mvnw -B package
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: balaji36490
      #     password: Balaji@280
      # # - name: Build Docker image
      # #   run: |
      # #     docker buildx build --tag balaji36490/petclinic:latest . --push