# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven latest

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:
    # inputs: 
    #   stages:
    #     description: 'Select the stages to run'
    #     required: true
    #     default: all
    #     type: choice
    #     options:
    #       - build
    #       - Docker
    #       - all
  push:
    branches:
      - main

jobs:
  # build:
  #   # if : ${{github.event.inputs.stages == 'build' || github.event.inputs.stages == 'all'}}

  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       java: [ '17' ]

  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         ref: main

  #     - name : checking the current folder
  #       run: pwd && ls -l


  #     - name: Set up JDK ${{matrix.java}}
  #       uses: actions/setup-java@v4
  #       with:
  #         java-version: ${{matrix.java}}
  #         distribution: 'adopt'
  #         cache: maven

  #     - name: installing maven
  #       run: |
  #           sudo apt-get update
  #           sudo apt-get install -y maven
  #           mvn --version 
  #     - name: build the project
  #       run: |
  #           mvn -B package --file ./spring-petclinic/pom.xml

  #     - name: view the test file
  #       run: |
  #           ls -l ./spring-petclinic/target/
  #           ls -l ./spring-petclinic/target/surefire-reports/
  #           cat ./spring-petclinic/target/surefire-reports/*.txt

  #     - name: publish artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: app-jar
  #         path: ./spring-petclinic/target/*.jar
  
  Docker: 
    # if : ${{github.event.inputs.stages == 'Docker' || github.event.inputs.stages == 'all'}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      # - name : download the artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: app-jar
      #     path: ./spring-petclinic/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "balaji36490"
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build Docker image
      #   run: |
      #     docker buildx build --platform linux/amd64 -t balaji36490/petclinic:12072025 ./spring-petclinic  --push

      # - name: Run Docker container
      #   run: |
      #     docker run -d --name petclinic-container -p 8080:8080 petclinic-image

      # - name: List running containers
      #   run: docker ps

     