name: Testing the azure connection

on: 
  workflow_dispatch:
  

permissions:
      contents: read
      id-token: write

jobs:
  test-azure-connection:
    runs-on: ubuntu-latest

    steps:
      - name: azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}  
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure kubernetes
        run: |
          az account show
          az aks get-credentials --resource-group petclinic-rg --name petclinic-aks
          kubectl get nodes
          kubectl get pods
